name: ci

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # need checkout before using docker-compose-remote-action
      - uses: actions/checkout@v2
      - uses: chaplyk/docker-compose-remote-action@v1.1
        with:
          ssh_host: 127.0.0.1
          ssh_user: username
          ssh_key: ${{ secrets.SSH_KEY }}
          compose_file: docker-compose.yml
          pull: true
          build: true