name: remote deploy to Server 1

on:
  workflow_dispatch:

env:
  SERVICE_PASSWORD: balance
  SERVICE_USER: balance
  SERVICE_DB: balance
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER1 }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: SERVICE_PASSWORD,SERVICE_USER,SERVICE_DB

          script: docker-compose up -d mongo