name: remote deploy to Server 1

on:
  workflow_dispatch:

env:
  SERVICE_PASSWORD: balance
  SERVICE_USER: balance
  SERVICE_DB: balance
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER1 }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: docker-compose up -d mongo
