name: remote deploy to Server 1

on:
  workflow_dispatch:


jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        env:
          SERVICE_PASSWORD: "balance"
          SERVICE_USER: "balance"
          SERVICE_DB: "balance"
          PROJECT_DIR: mongoinitializer
        with:
          host: ${{ secrets.SERVER1 }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          envs: SERVICE_PASSWORD,SERVICE_USER,SERVICE_DB,PROJECT_DIR
          script: |
            export SERVICE_PASSWORD=$SERVICE_PASSWORD
            export SERVICE_USER=$SERVICE_USER
            export SERVICE_DB=$SERVICE_DB
            export PROJECT_DIR=$PROJECT_DIR
            echo "SERVICE_PASSWORD: $SERVICE_PASSWORD"
            echo "SERVICE_USER: $SERVICE_USER"
            echo "SERVICE_DB: $SERVICE_DB"
            if [ -d mongoinitializer ]; then 
            rm -rf $PROJECT_DIR
            fi
            docker kill $(docker ps -q)
            docker rm -vf $(docker ps -a -q)
            docker rmi -f $(docker images -a -q)
            git clone https://github.com/demakovnik/mongoinitializer.git && cd $PROJECT_DIR && docker-compose up -d mongo --build
