name: remote deploy to Server 1

on:
  workflow_dispatch:


jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        env:
          SERVICE_PASSWORD: balance
          SERVICE_USER: balance
          SERVICE_DB: balance
        with:
          host: ${{ secrets.SERVER1 }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          envs: SERVICE_PASSWORD,SERVICE_USER,SERVICE_DB
          script: git clone https://github.com/demakovnik/mongoinitializer.git && cd mongoinitializer && docker-compose up -d mongo
