name: remote deploy to Server 1

on:
  workflow_dispatch:

env:
  SERVICE_PASSWORD: balance
  SERVICE_USER: balance
  SERVICE_DB: balance


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server 1
      - uses: actions/checkout@v2
      - uses: chaplyk/docker-compose-remote-action@v1.1
        with:
          ssh_host: ${{ secrets.SERVER1 }}
          ssh_user: ${{ secrets.SSH_USERNAME }}
          ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
          compose_file: docker-compose.yaml
          pull: true
          build: true